---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart semaphore
  systemd:
    name: semaphore
    state: restarted
    enabled: yes

- name: reload semaphore
  systemd:
    name: semaphore
    state: reloaded
