---
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: test nginx config
  command: nginx -t
  changed_when: false
