apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

bases:
  - ../../base

patchesStrategicMerge:
  - patches/grafana-deployment.yaml
  - patches/prometheus-deployment.yaml
  - patches/loki-statefulset.yaml
  - patches/tempo-statefulset.yaml

configMapGenerator:
  - name: environment-config
    literals:
      - ENVIRONMENT=staging
      - GKE_CLUSTER=checkinplus-staging
      - GKE_REGION=asia-southeast1
      - RETENTION_DAYS=30

secretGenerator:
  - name: grafana-admin
    literals:
      - username=admin
      - password=changeme123!  # Change this in production

resources:
  - grafana-ingress.yaml
  - certificates.yaml
  - network-policies.yaml

replicas:
  - name: grafana
    count: 2
  - name: prometheus
    count: 2

images:
  - name: grafana/grafana
    newTag: 10.2.3
  - name: prom/prometheus
    newTag: v2.48.0
  - name: grafana/loki
    newTag: 2.9.3
  - name: grafana/tempo
    newTag: 2.3.1
  - name: grafana/mimir
    newTag: 2.11.0

commonLabels:
  environment: staging
  managed-by: kustomize
