apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  type: ClusterIP
  ports:
  - port: 3101
    targetPort: http-metrics
    protocol: TCP
    name: http-metrics
  selector:
    app: promtail
