---
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ hostname }}"
  when: hostname is defined

- name: Configure timezone
  timezone:
    name: Asia/Bangkok

- name: Install common monitoring tools
  apt:
    name:
      - htop
      - iotop
      - netstat-nat
      - vnstat
      - iftop
      - sysstat
      - net-tools
      - dnsutils
      - traceroute
      - mtr
      - tcpdump
      - nmap
    state: present

- name: Configure sysctl for performance
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { name: 'net.core.somaxconn', value: '65535' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '8192' }
    - { name: 'net.core.netdev_max_backlog', value: '5000' }
    - { name: 'net.ipv4.tcp_fin_timeout', value: '30' }
    - { name: 'net.ipv4.tcp_keepalive_time', value: '300' }
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
    - { name: 'vm.max_map_count', value: '262144' }
    - { name: 'fs.file-max', value: '2097152' }

- name: Configure UFW firewall
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  when: configure_firewall | default(true)

- name: Allow SSH through UFW
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  when: configure_firewall | default(true)

- name: Configure logrotate for LGTM logs
  template:
    src: lgtm.logrotate.j2
    dest: /etc/logrotate.d/lgtm
    mode: '0644'

- name: Create systemd journal directory
  file:
    path: /var/log/journal
    state: directory
    mode: '0755'

- name: Configure systemd journal
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    mode: '0644'
    backup: yes
  notify: restart journald
