apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Namespace
  - namespace.yaml
  
  # Grafana
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/configmap.yaml
  - grafana/pvc.yaml
  - grafana/ingress.yaml
  - grafana/dashboards.yaml
  
  # Loki
  - loki/statefulset.yaml
  - loki/service.yaml
  - loki/configmap.yaml
  
  # Prometheus
  - prometheus/deployment.yaml
  - prometheus/configmap.yaml
  
  # OpenTelemetry
  - opentelemetry/configmap.yaml
  - opentelemetry/daemonset.yaml
  
  # Promtail (Log collector)
  - promtail/configmap.yaml
  - promtail/daemonset.yaml
  - promtail/service.yaml
  - promtail/serviceaccount.yaml
  - promtail/clusterrole.yaml
  - promtail/clusterrolebinding.yaml

commonLabels:
  app.kubernetes.io/part-of: lgtm-stack
  app.kubernetes.io/managed-by: kustomize
