apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    enable_gzip = true
    
    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db
    
    [security]
    disable_gravatar = true
    cookie_secure = true
    cookie_samesite = lax
    strict_transport_security = true
    x_content_type_options = true
    x_xss_protection = true
    
    [users]
    allow_sign_up = false
    allow_org_create = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    
    [auth]
    disable_login_form = false
    disable_signout_menu = false
    
    [auth.anonymous]
    enabled = false
    
    [analytics]
    reporting_enabled = false
    check_for_updates = false
    
    [explore]
    enabled = true
    
    [metrics]
    enabled = true
    interval_seconds = 10
    
    [tracing.jaeger]
    enabled = true
    address = tempo:6831
    sampler_type = const
    sampler_param = 1.0
    
    [feature_toggles]
    enable = tempoSearch tempoBackendSearch tempoServiceGraph
    
    [unified_alerting]
    enabled = true
    execute_alerts = true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - datasourceUid: tempo
              name: trace_id
        editable: true
      
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "trace_id=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
        editable: true
      
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        jsonData:
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: loki
          tracesToLogs:
            datasourceUid: loki
            filterByTraceID: true
            filterBySpanID: false
            mapTagNamesEnabled: true
            mappedTags:
              - key: service.name
                value: service
              - key: k8s.pod.name
                value: pod
              - key: k8s.namespace.name
                value: namespace
          serviceMap:
            datasourceUid: prometheus
        editable: true
      
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir:9009/prometheus
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - datasourceUid: tempo
              name: trace_id
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: monitoring
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
