---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes

- name: reload grafana
  systemd:
    name: grafana-server
    state: reloaded
